name: Rust

on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]

env:
  CARGO_TERM_COLOR: always

jobs:
  build:

    runs-on: windows-latest
    env:
      GH_TOKEN: ${{ github.token }}
    steps:
    - uses: actions/checkout@v4
    - name: Build
      run: cargo build --release
    - run: mkdir $RUNNER_TEMP\artifacts && cp target\release\dmfg_windows_setup.exe $RUNNER_TEMP\artifacts\dmfg_windows_setup_x64.exe
    - name: Github Release
      # You may pin to the exact commit or the version.
      # uses: elgohr/Github-Release-Action@c5ea99036abb741a89f8bf1f2cd7fba845e3313a
      uses: elgohr/Github-Release-Action@v5
      with:
        # The name of the release to publish
        title: latest release
        workdir: ${{ env.RUNNER_TEMP }}\artifacts
              
